name: Build And Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      commit-sha: ${{ steps.get-commit-sha.outputs.commit-sha}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          fetch-tags: false
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Restore/cache Go
        id: setup-go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Build and Race
        run: | 
          go build -v -race .
          go test -v ./...